version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0

    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install

      - run:
          name: run test
          command: yarn run test
      - run:
          name: coverage
          command: yarn run coverage

      - coveralls/upload
      - store_artifacts:
          path: test-results

      - store_artifacts:
          path: coverage

      - store_test_results:
          path: test-results

workflows:
  test-deploy:
    jobs:
      - build
